export const REQUEST_ADD_TODO = 'REQUEST_ADD_TODO';

export const RESPOND_ADD_TODO = 'RESPOND_ADD_TODO';

export const REQUEST_SET_TODOS = 'REQUEST_SET_TODOS';

export const RESPOND_SET_TODOS = 'RESPOND_SET_TODOS';

export const CHANGE_INPUT = 'CHANGE_INPUT';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';

export const RESPOND_LOGIN = 'RESPOND_LOGIN';

export const REJECT_LOGIN = 'REJECT_LOGIN';

export const AUTHENTICATE = 'AUTHENTICATE';

export const REQUEST_REGISTRATION = 'REQUEST_REGISTRATION';
